### PR TITLE
Added disk usage info

### PR DESCRIPTION
**Pull request by mgiannopoulos24**
- Added a function to get disk usage info .
- Removed `print_spaces()` for better format.

Expected output:

```console
System Information:
===================
Distribution: Ubuntu 22.
Kernel Version: 5.15.146.1-microsoft-standard-WSL2

Disk Usage:
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdc       1007G   14G  942G   2% /

URL:
String DOCUMENTATION_URL= not found!
```

### CODE REVIEW

**Comment by CoutHi** [comment]
I want to implement disk usage formatted more like:

-Distro
-Kernel
-etc.
.
.
- Disk (/): 14GiB/1007GiB
- Disk (/home):  50GiB/100GiB.
.
.

Also it'd be great if you start working on one of the features to first let me know, I'm working on this actively as well and wouldn't want to be implementing the same thing as you're working on.

And print_spaces() is just a placeholder function for now we don't need to worry about it yet. We'd be deleting all the print files at the end when we don't need to be doing any more debugging and come up with an approach to format the output with all the variables we have.

**Comment by mgiannopoulos24** [comment]
Okay I can fix the format as you want.

**Comment by mgiannopoulos24** [comment]
Try this. Do you like it?

**Comment by CoutHi** [comment]
Not what I intended, /home was an example. What I meant was that the program should find the mount directories in the system and print their usage.  Getting the mounted directories can be done with 'df -h --output=source,target' and filtering out temporary file systems etc. What we could then do is look up the disk usage of those directories and print them. Using df -h once more in the process to get the disk usage information.

**Comment by mgiannopoulos24** [comment]
Alright. I'm sorry.

**Comment by CoutHi** [comment]
After looking a bit more into df -h, there is no need to call it after filtering out the file systems and the ones we need, df -h --output=source,target,used,size prints all the info needed in one go. And there is no need to be sorry, we are two different people with two different ideas and have to explain them to each other, all part of the flow. Thank you for your contribution and your work so far.

**Comment by CoutHi** [comment]
just tried it out, the output wasn't long enough and is half the size of the output I get when running the command natively. I've also figured out the command which would enable you to filter out the filesystems we do not need (not real disks but are things like temporary filesystems) in the command itself without doing anything extra. You can get all the info you need with the command "df -h --output=source,target,used,size | grep -E '/dev/sd|/dev/nvme|/dev/hd|/dev/mmcb|/dev/mapper|/dev/vgname|/dev/vd|/dev/xvd'" which covers most type of storage devices out there as far as I know, this would save a lot of time and string manipulation. We can take a look and see if this version has issues with the length as well.

**Comment by mgiannopoulos24** [comment]
Okay then. I will take a look at `uptime`.  Maybe the `--pretty` flag is the one we need.

**Comment by CoutHi** [comment]
Very well, sorry it didn't work out with the merge request but I have implemented and pushed most of what you have done into the repo. Thank you for your contribution!

**Comment by mgiannopoulos24** [comment]
No problem. Could you add me on Discord?

**Comment by CoutHi** [comment]
Sure thing.

**Pull request closed without merging**
