### PR TITLE
Added terminal, locale, uptime info and alternative commands.

### PR DESCRIPTION
**Pull request by mgiannopoulos24**

### CODE REVIEW

**Comment by CoutHi** [comment]
I don't know where my previous comment went, but there is an issue with the locale output: 

LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=en_DE.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT=C
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

Besides that all is good.

**Comment by mgiannopoulos24** [comment]
What kind of issue? I added some alternative commands as comments if you dont like the current output.

**Comment by CoutHi** [comment]
It's too verbose as it is now. Localectl alternative one looks alright but an output in the way of en_GB-UTF or en_US-UTF etc. is not very clear. So I think we'll need a list of all the locales and assign the languages as strings to them manually. Which isn't really worth as of yet  when everything else is still in infancy. If you could remove the locale from the commit I'd be glad to merge the rest.

**Comment by mgiannopoulos24** [comment]
Sure one sec.

**Pull request closed without merging**
